[package]
name = "learn_rltk001"
version = "0.1.0"
authors = ["mimi <allthatjazz@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rltk = ">=0"
specs = ">=0"
specs-derive = ">=0"